### ISSUE TITLE
Request data to use in _example folder

### ISSUE THREAD

**Issue by hhapk** [berkanlafci/pyoat#2]
Hi, berkanlafci. Thank you for your fascinating works.
The repository 'pyoat', I know from the repository 'OADAT', which is also a outstanding work.
But I can not run the examples in 'pyoat', because the data is not released. 
Could you release the data in 'pyoat' in your free time? Or could you tell me that how the data in 'OADAT'  can be used in 'pyoat'?
Looking forward to your reply!

**Comment by firatozdemir** [comment]
Hi @hhapk
I'll respond to your question about OADAT: 
Can you have a look at our [oadat-evaluate](https://gitlab.renkulab.io/firat.ozdemir/oadat-evaluate) repo?   
In particular, under `Use data loaders to read a sample from datasets` in README, there is a [demo](https://gitlab.renkulab.io/firat.ozdemir/oadat-evaluate/-/blob/master/notebooks/read_data.ipynb) for reading an input/output scheme from OADAT dataset. 
You can download the dataset under `datasets_parent_dir`, then assign the OADAT subdataset for which you want to read samples from to `fname_dataset`. Then using desired `in_key` & `out_key` (need to use `raw` instead of `BP` channels to get signal matrices instead of reconstructions), you should be able to read OADAT and use it with pyoat.

**Comment by hhapk** [comment]
Thank you very much for your prompt reply. Following your prompts, I generated the system matrix using 'pyoat/_examples/exampleModel.py'. The system matrix runs smoothly in simulation.

Best regard!



At 2023-10-10 21:17:56, "Firat Ozdemir" ***@***.***> wrote:

Hi @hhapk
I'll respond to your question about OADAT:
Can you have a look at our oadat-evaluate repo?
In particular, under Use data loaders to read a sample from datasets in README, there is a demo for reading an input/output scheme from OADAT dataset.
You can download the dataset under datasets_parent_dir, then assign the OADAT subdataset for which you want to read samples from to fname_dataset. Then using desired in_key & out_key (need to use raw instead of BP channels to get signal matrices instead of reconstructions), you should be able to read OADAT and use it with pyoat.
